In [5]:
# Import numpy with alias np
import numpy as np

# normal in python without numpy
values = [1,2,3,4,5]
for i in range(len(values)):
    values[i] += 5

# now values holds [6,7,8,9,10]


In [6]:
print(values)

[6, 7, 8, 9, 10]


In [9]:
# Same example with numpy
values1 = [1,2,3,4,5]
result1 = np.array(values1) + 5


In [10]:
print(result1)

[ 6  7  8  9 10]


In [12]:
# same put direct with the matric
m1 = np.array(values1)
result2 = m1 + 5 

In [13]:
print(result2)

[ 6  7  8  9 10]


In [14]:
# numpy has a func this operation, this will return equal results
# x = np.multiply(some_array, 5)
# x = some_array * 5

In [15]:
# Element-wise Matrix Operations

# if the shape not equal:
# ValueError: operands could not be broadcast together with shapes .....

In [16]:
# equal shape
a1 = np.array([[1,3],[5,7]])
a1
# displays the following result:
# array([[1, 3],
#        [5, 7]])

b1 = np.array([[2,4],[6,8]])
b1
# displays the following result:
# array([[2, 4],
#        [6, 8]])

a1 + b1
# displays the following result
#      array([[ 3,  7],
#             [11, 15]])


array([[ 3,  7],
       [11, 15]])

In [17]:
# not equal shape 
a2 = np.array([[1,3],[5,7]])
a2
# displays the following result:
# array([[1, 3],
#        [5, 7]])
c2 = np.array([[2,3,6],[4,5,9],[1,8,7]])
c2
# displays the following result:
# array([[2, 3, 6],
#        [4, 5, 9],
#        [1, 8, 7]])

a2.shape
# displays the following result:
#  (2, 2)

c2.shape
# displays the following result:
#  (3, 3)

a2 + c2
# displays the following error:
# ValueError: operands could not be broadcast together with shapes (2,2) (3,3)

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 