In [18]:
# Matrix Product = func name ist matmul or dot for only 2 dimensions matrix
import numpy as np

In [19]:
# good shape example: [2,4] * [4,2]

a1 = np.array([[1,2,3,4],[5,6,7,8]])
a1
# displays the following result:
# array([[1, 2, 3, 4],
#        [5, 6, 7, 8]])
a1.shape
# displays the following result:
# (2, 4)

b1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b1
# displays the following result:
# array([[ 1,  2,  3],
#        [ 4,  5,  6],
#        [ 7,  8,  9],
#        [10, 11, 12]])
b1.shape
# displays the following result:
# (4, 3)

c1 = np.matmul(a1, b1)
print("values are: {result}".format(result=c1))
# displays the following result:
# array([[ 70,  80,  90],
#        [158, 184, 210]])
c1.shape
# displays the following result:
# (2, 3)

values are: [[ 70  80  90]
 [158 184 210]]


(2, 3)

In [21]:
# pad shape example: [4, 3] * [2, 4]
np.matmul(b1, a1)
# displays the following error:
# ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)